### ISSUE TITLE
Sala todo list as there is not project to place my stuff

### ISSUE THREAD

**Issue by saladuit** [MyNameIsTrez/transcendence#13]
SoreBoard

- [x] Refactor to composition api
- [ ] Scale Scoreboard to window size

**Comment by saladuit** [comment]
GameSocket
- [ ] Create a socket when user loads page
- [ ] Make a namespace for game data and one for user data, (perhaps one for chat)
- [ ] Create events for finding a game

**Comment by saladuit** [comment]
PlayButton
- [ ] Keep the start buttons center
- [ ] Remove PlayButton when game starts
- [ ] Place PlayButton in different file

**Comment by saladuit** [comment]
LeaveGameButton

Should this be added or only on defeat? Perhaps a return button? @BoredKeyboard @adfhjl

**Comment by saladuit** [comment]
Pong

- [ ] Resize paddles and ball to window size

**Comment by MyNameIsTrez** [comment]
Pong

- [ ] ball speed normaliseren

**Comment by MyNameIsTrez** [comment]
Moved all unresolved issues to [the new project board](https://github.com/users/MyNameIsTrez/projects/1).
